In [15]:
import pandas as pd
df = pd.read_csv("employees.csv")
df.head()

  emp_id    name department  age  salary  experience_yrs
0    E01   Aarav         IT   28   55000               3
1    E02  Bhavya         HR   32   48000               5
2    E03  Chirag         IT   26   52000               2
3    E04    Diya    Finance   35   72000               8
4    E05   Eshan         IT   30   60000               4

In [16]:
df.describe()

             age        salary  experience_yrs
count  10.000000     10.000000       10.000000
mean   31.800000  59200.000000        5.500000
std     4.709329  14505.171492        3.472111
min    26.000000  42000.000000        2.000000
25%    28.250000  49000.000000        3.000000
50%    31.000000  55000.000000        4.500000
75%    34.500000  69000.000000        7.500000
max    40.000000  85000.000000       12.000000

In [19]:
df.groupby('department')['salary'].mean()

department
Finance    78500.0
HR         45000.0
IT         61250.0
Sales      50000.0
Name: salary, dtype: float64

In [21]:
df.query("experience_yrs > 5")

  emp_id    name department  age  salary  experience_yrs
3    E04    Diya    Finance   35   72000               8
6    E07  Gaurav    Finance   40   85000              12
8    E09   Ishan      Sales   33   55000               6
9    E10    Jiya         IT   38   78000              10

In [23]:
df1 = df.sort_values("salary", ascending = False)
df1

  emp_id    name department  age  salary  experience_yrs
6    E07  Gaurav    Finance   40   85000              12
9    E10    Jiya         IT   38   78000              10
3    E04    Diya    Finance   35   72000               8
4    E05   Eshan         IT   30   60000               4
8    E09   Ishan      Sales   33   55000               6
0    E01   Aarav         IT   28   55000               3
2    E03  Chirag         IT   26   52000               2
1    E02  Bhavya         HR   32   48000               5
5    E06   Farah      Sales   29   45000               3
7    E08    Hina         HR   27   42000               2

In [24]:
df1.head(3)

  emp_id    name department  age  salary  experience_yrs
6    E07  Gaurav    Finance   40   85000              12
9    E10    Jiya         IT   38   78000              10
3    E04    Diya    Finance   35   72000               8

In [33]:
df['salary_per_year_exp'] = df.apply(lambda row: row['salary'] / row['experience_yrs'], axis=1)
df

  emp_id    name department  age  salary  experience_yrs  salary_per_year_exp
0    E01   Aarav         IT   28   55000               3         18333.333333
1    E02  Bhavya         HR   32   48000               5          9600.000000
2    E03  Chirag         IT   26   52000               2         26000.000000
3    E04    Diya    Finance   35   72000               8          9000.000000
4    E05   Eshan         IT   30   60000               4         15000.000000
5    E06   Farah      Sales   29   45000               3         15000.000000
6    E07  Gaurav    Finance   40   85000              12          7083.333333
7    E08    Hina         HR   27   42000               2         21000.000000
8    E09   Ishan      Sales   33   55000               6          9166.666667
9    E10    Jiya         IT   38   78000              10          7800.000000